### PR TITLE
Update yarprobotinterface_amti.xml

### PR DESCRIPTION
**Pull request by isorrentino**
Update ids platforms

### CODE REVIEW

**Comment by traversaro** [comment]
Why are we changing the order of the ids?

**Comment by InesSorrentino** [comment]
Check [this comment](https://github.com/dic-iit/component_andy/issues/211#issuecomment-487949489). 
Probably the cables connected to the platforms have been inverted, because on Nexus Vicon the platform 1 and 2 did not match to the real ones.

cc @claudia-lat

**Comment by traversaro** [comment]
Ack.

**Comment by traversaro** [comment]
Can we merge this change @fjandrad ?

**Comment by fjandrad** [comment]
@isorrentino Did we do some tests on this just to verify the ids? If yes then we can merge.

**Comment by isorrentino** [comment]
@fjandrad I did tests when I opened the PR. Then, I did not test it anymore.

**Comment by claudia-lat** [comment]
Since @isorrentino did the test, can we merge this PR @fjandrad?

**Comment by traversaro** [comment]
I guess we can merge this, if necessary we can always revert this PR.

**Pull request merged**
